In [1]:
import pandas as pd
import numpy as np
import sklearn as sns

In [2]:
df = pd.read_csv("laptopPrice.csv")

In [3]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0


In [4]:
df.duplicated().sum()

np.int64(21)

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    str  
 1   processor_brand    802 non-null    str  
 2   processor_name     802 non-null    str  
 3   processor_gnrtn    802 non-null    str  
 4   ram_gb             802 non-null    str  
 5   ram_type           802 non-null    str  
 6   ssd                802 non-null    str  
 7   hdd                802 non-null    str  
 8   os                 802 non-null    str  
 9   os_bit             802 non-null    str  
 10  graphic_card_gb    802 non-null    str  
 11  weight             802 non-null    str  
 12  warranty           802 non-null    str  
 13  Touchscreen        802 non-null    str  
 14  msoffice           802 non-null    str  
 15  Price              802 non-null    int64
 16  rating             802 non-null    str  
 17  Number of Ratings  802 non-null 

In [8]:
df['brand'].unique()

<StringArray>
['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE']
Length: 8, dtype: str

In [9]:
df['processor_brand'].unique()

<StringArray>
['Intel', 'AMD', 'M1']
Length: 3, dtype: str

In [10]:
processor_brand ={
    'Intel':1, 'AMD':2, 'M1':3
}

In [11]:
df['processor_brand']=df['processor_brand'].map(processor_brand)

In [12]:
df['processor_name'].unique()

<StringArray>
[     'Core i3',      'Core i5', 'Celeron Dual',      'Ryzen 5',
      'Core i7',      'Core i9',           'M1', 'Pentium Quad',
      'Ryzen 3',      'Ryzen 7',      'Ryzen 9']
Length: 11, dtype: str

In [13]:
processor_name ={
     'Core i3':1,      'Core i5':2, 'Celeron Dual':3,      'Ryzen 5':4,
      'Core i7':5,      'Core i9':6,           'M1':7, 'Pentium Quad':8,
      'Ryzen 3':9,      'Ryzen 7':10,      'Ryzen 9':11
}

In [14]:
df['processor_name']=df['processor_name'].map(processor_name)

In [15]:
df['processor_gnrtn'].unique()

<StringArray>
['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th', '12th']
Length: 8, dtype: str

In [16]:
processor_gnrtn ={
    '10th':10, 'Not Available':0, '11th':11, '7th':7, '8th':8, '9th':9, '4th':4, '12th':12
}

In [17]:
df['processor_gnrtn']=df['processor_gnrtn'].map(processor_gnrtn)

In [18]:
df['ram_gb'].unique()

<StringArray>
['4 GB', '8 GB', '16 GB', '32 GB']
Length: 4, dtype: str

In [19]:
ram_gb ={
    '4 GB':4, '8 GB':8, '16 GB':16, '32 GB':32
}

In [20]:
df['ram_gb']=df['ram_gb'].map(ram_gb)

In [21]:
df['ram_type'].unique()

<StringArray>
['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3']
Length: 6, dtype: str

In [22]:
ram_type ={
    'DDR4':1, 'LPDDR4':2, 'LPDDR4X':3, 'DDR5':4, 'DDR3':5, 'LPDDR3':6
}

In [23]:
df['ram_type']=df['ram_type'].map(ram_type)

In [24]:
df['ssd'].unique()

<StringArray>
['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB', '3072 GB']
Length: 7, dtype: str

In [25]:
ssd ={
    '0 GB':0, '512 GB':512, '256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048, '3072 GB':3072
}

In [26]:
df['ssd']=df['ssd'].map(ssd)

In [27]:
df['hdd'].unique()

<StringArray>
['1024 GB', '0 GB', '512 GB', '2048 GB']
Length: 4, dtype: str

In [28]:
hdd ={
    '0 GB':0, '512 GB':512, '256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048, '3072 GB':3072
}

In [29]:
df['hdd']=df['hdd'].map(hdd)

In [30]:
df['os'].unique()

<StringArray>
['Windows', 'DOS', 'Mac']
Length: 3, dtype: str

In [31]:
os ={
    'Windows':1, 'DOS':2, 'Mac':3
}

In [32]:
df['os']=df['os'].map(os)

In [33]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,1,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,1,1,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,1,1,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,1,2,10,8,1,512,0,1,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,1,3,0,4,1,0,512,1,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,11,0,4,1,1024,0,1,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,2,11,0,4,1,1024,0,1,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,2,11,0,4,1,1024,0,1,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,2,11,0,4,1,1024,0,1,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0


In [34]:
df['os_bit'].unique()

<StringArray>
['64-bit', '32-bit']
Length: 2, dtype: str

In [35]:
os_bit ={
    '64-bit':64, '32-bit':32
}

In [36]:
df['os_bit']=df['os_bit'].map(os_bit)

In [37]:
df['graphic_card_gb'].unique()

<StringArray>
['0 GB', '2 GB', '4 GB', '6 GB', '8 GB']
Length: 5, dtype: str

In [38]:
graphic_card_gb ={
    '0 GB':0, '2 GB':2, '4 GB':4, '6 GB':6, '8 GB':8
}

In [39]:
df['graphic_card_gb']=df['graphic_card_gb'].map(graphic_card_gb)

In [40]:
df['weight'].unique()

<StringArray>
['Casual', 'ThinNlight', 'Gaming']
Length: 3, dtype: str

In [41]:
weight ={
    'Casual':0, 'ThinNlight':1, 'Gaming':2
}

In [42]:
df['weight']=df['weight'].map(weight)

In [43]:
df['warranty'].unique()

<StringArray>
['No warranty', '1 year', '2 years', '3 years']
Length: 4, dtype: str

In [44]:
warranty ={
    'No warranty':0, '1 year':1, '2 years':2, '3 years':3
}

In [45]:
df['warranty']=df['warranty'].map(warranty)

In [46]:
df['Touchscreen'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [47]:
Touchscreen ={
    'No':0, 'Yes':1
}

In [48]:
df['Touchscreen']=df['Touchscreen'].map(Touchscreen)

In [49]:
df['msoffice'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [50]:
msoffice ={
    'No':0, 'Yes':1
}
df['msoffice']=df['msoffice'].map(msoffice)

In [51]:
df['Price'].unique()

array([ 34649,  38999,  39999,  69990,  26990,  22990,  21990,  58799,
        49999,  59990,  93700,  72990,  17490,  35990,  56490,  65390,
        31999,  32490,  31799,  29890,  23990,  32955,  46200,  34429,
        37990,  33980,  39990,  39490,  53990,  38990,  37890,  41990,
        45990,  42490,  36990,  38940,  42990,  49990,  41490,  38490,
        44990,  36490,  38970,  44900,  44427,  40200,  40990,  71999,
        41998,  39998,  48490,  44376,  43900,  46690,  43990,  48500,
        48990,  23490,  54238,  51990,  43970,  54990,  41250,  60790,
        45650,  45490,  38799,  69267,  51649,  47990,  44890,  50990,
        48900,  41790,  57999,  45930,  55490,  32890,  42190,  43690,
        43800,  34990,  38900,  40890,  39790,  35590,  33990,  43400,
        24990,  40750,  43000,  38000,  49279,  41500,  36999,  42900,
        21490,  41480,  32990,  38680,  40390,  20490,  44490,  41890,
        43590,  44690,  41390,  44290,  48999,  46390,  18990,  17990,
      

In [52]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,34649,2 stars,3,0
1,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,38999,3 stars,65,5
2,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,39999,3 stars,8,1
3,ASUS,1,2,10,8,1,512,0,1,32,2,0,0,0,0,69990,3 stars,0,0
4,ASUS,1,3,0,4,1,0,512,1,64,0,0,0,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,135990,3 stars,0,0
819,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,144990,3 stars,0,0
820,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,149990,3 stars,0,0
821,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,142990,3 stars,0,0


In [53]:
df['rating'].unique()

<StringArray>
['2 stars', '3 stars', '4 stars', '5 stars', '1 star']
Length: 5, dtype: str

In [54]:
rating ={
    '2 stars':2, '3 stars':3, '4 stars':4, '5 stars':5, '1 star':1
}

In [55]:
df['rating']=df['rating'].map(rating)

In [56]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,34649,2,3,0
1,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,38999,3,65,5
2,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,39999,3,8,1
3,ASUS,1,2,10,8,1,512,0,1,32,2,0,0,0,0,69990,3,0,0
4,ASUS,1,3,0,4,1,0,512,1,64,0,0,0,0,0,26990,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,135990,3,0,0
819,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,144990,3,0,0
820,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,149990,3,0,0
821,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,142990,3,0,0


In [57]:
x = df.drop(['Price', 'brand'], axis=1)
y = df['Price']

In [58]:
x.duplicated().sum()

np.int64(48)

In [59]:
#x.drop_duplicates(inplace=True)

In [60]:
y.duplicated().sum()

np.int64(397)

In [61]:
#y.drop_duplicates(inplace=True)

In [62]:
df.info()

<class 'pandas.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    str  
 1   processor_brand    802 non-null    int64
 2   processor_name     802 non-null    int64
 3   processor_gnrtn    802 non-null    int64
 4   ram_gb             802 non-null    int64
 5   ram_type           802 non-null    int64
 6   ssd                802 non-null    int64
 7   hdd                802 non-null    int64
 8   os                 802 non-null    int64
 9   os_bit             802 non-null    int64
 10  graphic_card_gb    802 non-null    int64
 11  weight             802 non-null    int64
 12  warranty           802 non-null    int64
 13  Touchscreen        802 non-null    int64
 14  msoffice           802 non-null    int64
 15  Price              802 non-null    int64
 16  rating             802 non-null    int64
 17  Number of Ratings  802 non-null 

In [63]:
x

,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews
0,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,2,3,0
1,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,3,65,5
2,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,3,8,1
3,1,2,10,8,1,512,0,1,32,2,0,0,0,0,3,0,0
4,1,3,0,4,1,0,512,1,64,0,0,0,0,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,3,0,0
819,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,3,0,0
820,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,3,0,0
821,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,3,0,0


In [64]:
y

0       34649
1       38999
2       39999
3       69990
4       26990
        ...  
818    135990
819    144990
820    149990
821    142990
822     57490
Name: Price, Length: 802, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [66]:
x_train, y_train, x_test, y_test = x_train, y_train, x_test, y_test.drop_duplicates()

In [67]:
x_test

,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews
196,1,2,0,8,4,0,512,1,32,4,0,0,0,0,4,10966,1185
299,1,2,11,8,3,512,0,1,32,0,0,1,0,1,4,76,14
171,1,1,10,8,1,256,1024,1,64,0,1,1,0,1,5,7,5
537,1,5,10,16,1,1024,0,1,64,6,0,1,0,1,4,17,4
551,1,5,11,16,1,1024,0,1,64,8,0,2,0,0,4,14,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,1,2,11,8,3,512,0,1,64,0,0,1,1,0,3,0,0
361,1,2,10,8,1,512,0,1,64,0,0,1,1,0,5,2,1
446,1,2,11,8,1,256,1024,1,64,0,0,1,0,0,4,47,0
767,2,10,0,4,1,512,0,1,64,4,0,1,0,0,3,0,0


In [68]:
x_train

,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews
442,1,2,11,8,1,256,1024,1,32,0,0,1,0,1,4,1188,127
598,1,5,10,16,3,0,512,2,32,6,0,0,0,0,3,2,1
452,1,2,11,8,1,256,1024,1,64,2,0,1,0,1,4,33,4
696,2,4,0,8,1,512,0,1,64,0,1,1,0,1,3,0,0
339,1,2,11,8,3,512,0,1,64,0,0,1,1,0,4,35,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,1,1,10,4,1,256,0,1,32,0,0,0,0,0,3,3,0
108,1,1,11,8,1,512,0,1,64,0,0,1,1,0,4,10,1
275,1,2,10,8,1,512,0,1,64,2,0,1,0,1,3,0,0
445,1,2,11,8,1,256,1024,1,64,0,0,1,0,0,3,0,0


In [69]:
y_test

196     50990
299     72990
171     41490
537    144690
551    129990
        ...  
258     47990
588    139990
361    126000
767    106990
529    110999
Name: Price, Length: 115, dtype: int64

In [70]:
y_train

442     50990
598    146490
452     60190
696     59490
339     99990
        ...  
73      41990
108     60790
275     57500
445     52990
104     44990
Name: Price, Length: 641, dtype: int64

In [71]:
#from sklearn.linear_model import LinearRegression
#lr = LinearRegression()

In [73]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,34649,2,3,0
1,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,38999,3,65,5
2,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,39999,3,8,1
3,ASUS,1,2,10,8,1,512,0,1,32,2,0,0,0,0,69990,3,0,0
4,ASUS,1,3,0,4,1,0,512,1,64,0,0,0,0,0,26990,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,135990,3,0,0
819,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,144990,3,0,0
820,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,149990,3,0,0
821,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,142990,3,0,0


In [74]:
df.duplicated().sum()

np.int64(0)

In [77]:
from sklearn.svm import SVR
sv = SVR()

In [ ]:
sv.fit(x_train, y_train)

,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm.If none is given, 'rbf' will be used. If a callable is given it isused to precompute the kernel matrix.For an intuitive visualization of different kernel typessee :ref:`sphx_glr_auto_examples_svm_plot_svm_regression.py`",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.The penalty is a squared l2. For an intuitive visualization of theeffects of scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"epsilon epsilon: float, default=0.1Epsilon in the epsilon-SVR model. It specifies the epsilon-tubewithin which no penalty is associated in the training loss functionwith points predicted within a distance epsilon from the actualvalue. Must be non-negative.",0.1
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False
,"max_iter max_iter: int, default=-1Hard limit on iterations within solver, or -1 for no limit.",-1


In [ ]:
pred =sv.predict(x_test)
pred


array([64028.7919338 , 64089.50255335, 63996.70923421, 64119.39478548,
       64119.44311433, 64119.58053168, 64029.05616895, 64091.44354151,
       64089.30750509, 64055.6243796 , 64068.49272706, 63979.25185903,
       64091.54090069, 64119.63566041, 64090.46189989, 64013.10950745,
       64091.47009768, 64090.4972203 , 64091.44364688, 64119.60704098,
       63979.12469812, 64068.5215641 , 64091.19168443, 64066.46735922,
       64018.02722537, 64068.527047  , 64081.27401076, 64119.6515303 ,
       64067.69154945, 64068.52155596, 63996.19697743, 64090.41297056,
       63989.67021054, 64091.53306879, 64091.41787153, 64067.5846179 ,
       64086.89117286, 64091.30955551, 64065.84660834, 64091.10747064,
       64047.27127282, 64070.68522923, 64090.43933548, 63983.89140293,
       64090.44248239, 64068.43371696, 64119.45340769, 64091.52614274,
       64105.64128543, 63996.88239793, 64091.54269732, 64013.29797804,
       64013.29577283, 64091.4483115 , 64085.12913513, 64119.64687758,
      

In [ ]:
pred[0:100]

array([64028.7919338 , 64089.50255335, 63996.70923421, 64119.39478548,
       64119.44311433, 64119.58053168, 64029.05616895, 64091.44354151,
       64089.30750509, 64055.6243796 , 64068.49272706, 63979.25185903,
       64091.54090069, 64119.63566041, 64090.46189989, 64013.10950745,
       64091.47009768, 64090.4972203 , 64091.44364688, 64119.60704098,
       63979.12469812, 64068.5215641 , 64091.19168443, 64066.46735922,
       64018.02722537, 64068.527047  , 64081.27401076, 64119.6515303 ,
       64067.69154945, 64068.52155596, 63996.19697743, 64090.41297056,
       63989.67021054, 64091.53306879, 64091.41787153, 64067.5846179 ,
       64086.89117286, 64091.30955551, 64065.84660834, 64091.10747064,
       64047.27127282, 64070.68522923, 64090.43933548, 63983.89140293,
       64090.44248239, 64068.43371696, 64119.45340769, 64091.52614274,
       64105.64128543, 63996.88239793, 64091.54269732, 64013.29797804,
       64013.29577283, 64091.4483115 , 64085.12913513, 64119.64687758,
      

In [ ]:
sv.score(x_train, y_train)

-0.0649275866046346

In [ ]:
lr

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [ ]:
print(x_train.shape)
print(y_train.shape)

(641, 17)
(641,)


In [ ]:
y_train =y_train.values.ravel()

In [ ]:
import imblearn
from imblearn.over_sampling import SMOTE

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Apply SMOTE to the training data
sm = SMOTE(random_state=42)


In [ ]:
pred =sv.predict(x_test)
pred


array([64028.7919338 , 64089.50255335, 63996.70923421, 64119.39478548,
       64119.44311433, 64119.58053168, 64029.05616895, 64091.44354151,
       64089.30750509, 64055.6243796 , 64068.49272706, 63979.25185903,
       64091.54090069, 64119.63566041, 64090.46189989, 64013.10950745,
       64091.47009768, 64090.4972203 , 64091.44364688, 64119.60704098,
       63979.12469812, 64068.5215641 , 64091.19168443, 64066.46735922,
       64018.02722537, 64068.527047  , 64081.27401076, 64119.6515303 ,
       64067.69154945, 64068.52155596, 63996.19697743, 64090.41297056,
       63989.67021054, 64091.53306879, 64091.41787153, 64067.5846179 ,
       64086.89117286, 64091.30955551, 64065.84660834, 64091.10747064,
       64047.27127282, 64070.68522923, 64090.43933548, 63983.89140293,
       64090.44248239, 64068.43371696, 64119.45340769, 64091.52614274,
       64105.64128543, 63996.88239793, 64091.54269732, 64013.29797804,
       64013.29577283, 64091.4483115 , 64085.12913513, 64119.64687758,
      

In [ ]:
pred[0:20]

array([64028.7919338 , 64089.50255335, 63996.70923421, 64119.39478548,
       64119.44311433, 64119.58053168, 64029.05616895, 64091.44354151,
       64089.30750509, 64055.6243796 , 64068.49272706, 63979.25185903,
       64091.54090069, 64119.63566041, 64090.46189989, 64013.10950745,
       64091.47009768, 64090.4972203 , 64091.44364688, 64119.60704098])

In [ ]:
y_test[0:20]

196     50990
299     72990
171     41490
537    144690
551    129990
809    142990
610    104990
328     64990
222     51990
415    125394
68      41990
658     32917
239     65990
819    144990
758     57999
433    291190
316    106490
111     45490
280     61290
544    154990
Name: Price, dtype: int64